pidfile "/var/run/milter-greylist/milter-greylist.pid"
dumpfile "/var/lib/milter-greylist/greylist.db" 600
dumpfreq 1
user "smmsp"
quiet
stat "|cat" "%T{%Y/%m/%d %T} %d [%i] %f -> %r %S (ACL %A) %Xc %Xe %Xm"
racl greylist default
